### ISSUE TITLE
Fairly new to Docker. How to setup the whole folder structure to get Wordpress + Sage working.

### ISSUE THREAD

**Issue by mvaneijgen** [aaemnnosttv/docker-sage-build#1]
Last year I tried to get Sage 9 working on my local machine (spoiler alert I couldn't get is to work) and this screwed up my whole developer setup for Sage 8. Now around me I see a lot of people using Docker, but I just don't know where to start to move over my Wordpress workflow to Docker. 

I am now using AMPPS which has Softaculous installed to install Wordpress with one click, but installing manually isn't that difficult if you can get a local server to work, but how do you start by setting this up for Docker and where does your `dockerfile` come in to play? 

Maybe this is the wrong place to ask, if this is the case just close this issue. But I would love to see a way someone is already uses Docker + Wordpress + Sage to help me get started.

**Comment by mvaneijgen** [comment]
It took me a fair bit of my weekend and a lot of reading, trail and error and a bit of luck, but I finally got docker running with a persistent database, exposed (and persistent) Wordpress core and your Docker image installed. Now I only need to know where I can run my commands like `gulp watch` so that it runs in the Docker container and not on my host machine. 

The `docker-compose.yml` file I use https://gist.github.com/mvaneijgen/bba2be189a3787fcc326dbff56934171

**Comment by aaemnnosttv** [comment]
Hi there! This image isn't really intended to be used as part of a stack assembled with Compose as it doesn't really provide a service. You could still use it to build a site you were running with a docker compose setup, but the usage would be the same.

To be honest, this image is more relevant for Sage 8. There was a time when the dependencies required a more specific Node version, and this image took care of the global dependencies needed such as Gulp and Bower. The image for Sage 9 is a simple wrapper around npm and not much more than that. You could likely substitute it for the official Node image itself (even comes with Yarn pre-installed now), or just use something like [NVM](https://github.com/creationix/nvm). Sage 9 has been a long time in the works and as it turns out it doesn't require anything special to build you can't install with a simple `npm install`.

I've updated and tested both images to make sure they both work but I'm afraid I can't be of more help as to how to set things up in your case.
